rest-server:
  word-search: http://plus.kipris.or.kr/kipo-api/kipi/patUtiModInfoSearchSevice/getWordSearch
  claim-search: http://plus.kipris.or.kr/kipo-api/kipi/patUtiModInfoSearchSevice/getBibliographyDetailInfoSearch
  api-key: ""
  row: 500

database:
  address: mongodb://localhost
  database: Patent
  collection: claim

port: 12354
version: "1.2a1"